<?php

/**
 * Implements hook_field_info().
 */
function base_min_max_field_info() {
  return [
    'baseminmax' => [
      'label' => t('Base/Min/Max'),
      'description' => t('This field stores three values: a base value, and minimum and maximum values for searching.'),
      'settings' => [
        'type' => 'numeric'
      ],
      'instance_settings' => [
        'min_base' => 0,
        'max_base' => 100,
        'min_minimum' => 0,
        'max_minimum' => 100,
        'min_maximum' => 0,
        'max_maximum' => 100,
      ],
      'default_widget' => 'baseminmax_combined',
      'default_formatter' => 'baseminmax_default',
    ],
  ];
}

/**
 * Implements hook_field_schema().
 * @param $field
 * @return null|array
 * @throws \Exception
 */
function base_min_max_field_schema($field) {
  $schema = null;
  if($field['type'] == 'baseminmax') {
    $schema = [];

    $columnType = $field['settings']['type'];
    if($columnType == 'numeric') {
      $typeSpecificSettings = [
        'type' => $columnType,
        'size' => 'normal',
        'precision' => 10,
        'scale' => 2,
        'default' => 0,
        'not null' => false,
      ];
    } else if ($columnType == 'varchar') {
      $typeSpecificSettings = [
        'type' => $columnType,
        'length' => 255,
        'size' => 'normal',
        'default' => '',
        'not null' => false,
      ];
    } else {
      throw new \Exception("Unknow column type!");
    }

    $schema['columns']['base'] = $typeSpecificSettings;
    $schema['columns']['minimum'] = $typeSpecificSettings;
    $schema['columns']['maximum'] = $typeSpecificSettings;

    $schema['indexes'] = [
      'base' => ['base'],
      'minimum' => ['minimum'],
      'maximum' => ['maximum'],
    ];
  }
  return $schema;
}

/**
 * Implements hook_field_is_empty().
 * @param array $item
 * @param array $field
 * @return boolean
 */
function base_min_max_field_is_empty($item, $field) {
  $answer = false;
  if($field['type'] == 'baseminmax') {
    $answer = !strlen($item['base']) && !strlen($item['minimum']) && !strlen($item['maximum']);
  }
  return $answer;
}

/**
 * Implements hook_field_settings_form().
 */
function base_min_max_field_settings_form($field, $instance, $has_data) {
  $settings = $field['settings'];
  $form = [];

  if(!$has_data) {
    $form['type'] = [
      '#type' => 'select',
      '#title' => t('Data Type'),
      '#options' => [
        'numeric' => t('Numeric'),
        'varchar' => t('Textual'),
      ],
      '#default_value' => $settings['type'],
      '#required' => true,
      '#description' => t('Select what type of data you want to store in this field. '
                          .'Numeric type fields can be used as slider/range filters in views.'),
    ];
  } else {
    $typeName = ($settings['type']=="numeric" ? "Numeric" : "Textual");
    $form['type'] = [
      '#markup' => t('Type: %type', ['%type' => $typeName]),
    ];
  }
  return $form;
}

/**
 * Disable cardinality
 * @param array $form
 * @param array $form_state
 * @param string $form_id
 */
function base_min_max_form_field_ui_field_edit_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#field']['type'] == 'baseminmax') {
    $form['field']['cardinality'] = [
      '#type' => 'hidden',
      '#value' => 1,
    ];
  }
}

/**
 * Implements hook_field_widget_info().
 * @return array
 */
function base_min_max_field_widget_info() {
  return [
    'baseminmax_simple' => [
      'label' => t('Base Min Max - Separate Fields'),
      'description' => t('Enter data separately'),
      'field types' => ['baseminmax'],
      'behaviors' => [
        'multiple values' => FIELD_BEHAVIOR_DEFAULT,
        'default value' => FIELD_BEHAVIOR_DEFAULT,
      ],
    ],
  ];
}

/**
 * Implements hook_field_widget_form().
 */
function base_min_max_field_widget_form(&$form, &$form_state, $field, $instance,
                                        $langcode, $items, $delta, $element) {
  if ($instance['widget']['type'] == 'baseminmax_simple') {

    $form['#attached']['css'][] = drupal_get_path('module', 'base_min_max') . '/css/base_min_max.less';

    $element += [
        '#type' => 'fieldset',
        '#element_validate' => ['_base_min_max_field_validate_custom'],
        '#collapsible' => false,
        '#attributes' => [
          'class' => ['baseminmax-fieldset', 'container-inline'],
        ]
    ];

    $element['base'] = [
      '#type' => 'textfield',
      '#required' => false,
      '#title' => t('Base'),
      '#default_value' => isset($items[$delta]['base']) ? $items[$delta]['base'] : NULL,
      '#weight' => 1,
      '#size' => 10,
      '#attributes' => [
        'class' => ['text-right'],
      ],
    ];

    $element['minimum'] = [
      '#type' => 'textfield',
      '#required' => false,
      '#title' => t('Minimum'),
      '#default_value' => isset($items[$delta]['minimum']) ? $items[$delta]['minimum'] : NULL,
      '#weight' => 2,
      '#size' => 10,
      '#attributes' => [
        'class' => ['text-right'],
      ],
    ];

    $element['maximum'] = [
      '#type' => 'textfield',
      '#required' => false,
      '#title' => t('Maximum'),
      '#default_value' => isset($items[$delta]['maximum']) ? $items[$delta]['maximum'] : NULL,
      '#weight' => 3,
      '#size' => 10,
      '#attributes' => [
        'class' => ['text-right'],
      ],
    ];
  }

  return $element;
}

/**
 * @param array $element
 * @param array $form_state
 */
function _base_min_max_field_validate_custom($element, &$form_state) {
  if ($form_state['complete form']['#form_id'] == 'field_ui_field_edit_form') {
    return;
  }

  $values = $form_state['values'];
  $field_name = $element['#field_name'];
  $language = isset($values[$field_name][$values['language']]) ? $values['language'] : 'und';
  $fieldType = $form_state['field'][$field_name][$language]['field']['settings']['type'];


  if ($fieldType == 'numeric') {
    $columns = [
      'base' => 'base',
      'minimum' => 'minimum',
      'maximum' => 'maximum',
    ];
    foreach ($values[$field_name][$language] as $delta => $item) {
      foreach ($columns as $column_name => $column_data) {
        if (empty($item[$column_name])) {
          $baseValue = floatval($item["base"]);
          $item[$column_name] = $baseValue;
        } else {
          $columnValue = floatval($item[$column_name]);
          $item[$column_name] = $columnValue;
        }
      }
      form_set_value($element, $item, $form_state);
    }
  }
}

/**
 * Implements hook_field_validate().
 */
function base_min_max_field_validate($entity_type, $entity, $field, $instance,
                                     $langcode, $items, &$errors) {
  // This must be the field configuration form
  if(!$entity_type) {
    return;
  }

  if($field['type'] == 'baseminmax' && $field['settings']['type'] == 'numeric') {
    foreach ($items as $delta => &$item) {

      if(!strlen($item['base'])) {
        $errors[$field['field_name']][$langcode][$delta][] = [
          'error' => 'baseminmax_' . 'base',
          'message' => t('%field - Base value cannot be empty.', [
            '%field' => $instance['label'],
          ]),
        ];
      }

      if($item['minimum'] > $item['base'] || $item['minimum'] > $item['maximum']) {
        $errors[$field['field_name']][$langcode][$delta][] = [
          'error' => 'baseminmax_' . 'minimum',
          'message' => t('%field - Minimum must be smaller than base or maximum.', [
            '%field' => $instance['label'],
          ]),
        ];
      }

      if($item['maximum'] < $item['minimum'] || $item['maximum'] < $item['base']) {
        $errors[$field['field_name']][$langcode][$delta][] = [
          'error' => 'baseminmax_' . 'maximum',
          'message' => t('%field - Maximum must be bigger than base or minimum.', [
            '%field' => $instance['label'],
          ]),
        ];
      }

    }
  }
}

/**
 * Implements hook_field_formatter_info().
 */
function base_min_max_field_formatter_info() {
  return [
    'base_min_max_default' => [
      'label' => t('Default'),
      'field types' => ['baseminmax'],
    ],
    'base_min_max_json' => [
      'label' => t('JSON'),
      'field types' => ['baseminmax'],
    ],
  ];
}

/**
 * Implements hook_field_formatter_view().
 * @return array
 */
function base_min_max_field_formatter_view($entity_type, $entity, $field,
                                           $instance, $langcode, $items,
                                           $display) {
  $element = [];
  //$settings = $display['settings'];
  switch ($display['type']) {
    case 'base_min_max_default':
      foreach ($items as $delta => $item) {
        $output = t('Base: %base, Min: %minimum, Max: %maximum', [
          '%base' =>  $item['base'],
          '%minimum' =>  $item['minimum'],
          '%maximum' =>  $item['maximum'],
        ]);
        $element[$delta] = array('#markup' => $output);
      }
      break;
    case 'base_min_max_json':
      foreach ($items as $delta => $item) {
        $output = json_encode($item);
        $element[$delta] = array('#markup' => $output);
      }
      break;
  }
  return $element;
}

/**
 * Implements hook_views_api().
 */
function base_min_max_views_api() {
  return [
    'api' => 3,
    'path' => drupal_get_path('module', 'base_min_max') . '/views',
  ];
}


/**
 * Enable field handling for Feeds for this field type
 *
 * Implements hook_feeds_processor_targets_alter().
 * @param array &$targets
 *   Array containing the targets to be offered to the user. Add to this array
 *   to expose additional options.
 * @param string $entity_type
 *   The entity type of the target, for instance a 'node' entity.
 * @param string $bundle
 *   The entity bundle to return targets for.
 */
function base_min_max_feeds_processor_targets_alter(array &$targets, $entity_type, $bundle) {
  foreach (field_info_instances($entity_type, $bundle) as $fieldName => $fieldInstance) {
    $fieldInfo = field_info_field($fieldName);
    if ($fieldInfo['type'] == 'baseminmax') {
      foreach(['', 'base', 'minimum', 'maximum'] as $type) {
        $targets[$fieldName . ($type ? ':'.$type : '')] = [
          'name' => t('@label@type', array('@label' => check_plain($fieldInstance['label']), '@type' => ($type ? ': '.ucfirst($type) : ''))),
          'callback' => 'base_min_max_feeds_field_baseminmax_set_target',
          'description' => t('The @typedesc @label field of the node.',
                             [
                               '@label' => $fieldInstance['label'],
                               '@typedesc' => ($type ? ucfirst($type) . ' ' . t('of the') . ' ' : ''),
                             ])
        ];
      }
    }
  }
}

function base_min_max_feeds_field_baseminmax_set_target(\FeedsSource $source, $entity, $target, array $values, array $mapping) {
  list($field_name, $sub_field) = explode(':', $target);
  $field = isset($entity->$field_name) ? $entity->$field_name : ['und' => []];
  $fieldInfo = field_info_field($field_name);
  $fieldType = $fieldInfo['settings']['type'];
  $isNumeric = $fieldType == 'numeric';

  // Iterate over all values.
  $delta = 0;
  foreach ($values as $value) {
    if (is_scalar($value) && strlen($value)) {
      if(strpos($value, ",")) {
        throw new Exception(
          t('You cannot use "," character for this field(%fieldname)! '
            . ' The decimal separator is "." and the Base|Min|Max separator is "|".',
            ['%fieldname' => $field_name]
          )
        );
      }
      if(!$sub_field) {
        list($baseVal, $minVal, $maxVal) = explode('|', $value);
        $minVal = $minVal ? $minVal : $baseVal;
        $maxVal = $maxVal ? $maxVal : $baseVal;
        if($isNumeric) {
          $baseVal = floatval($baseVal);
          $minVal = floatval($minVal);
          $maxVal = floatval($maxVal);
        }
        $field['und'][$delta]['base'] = $baseVal;
        $field['und'][$delta]['minimum'] = $minVal;
        $field['und'][$delta]['maximum'] = $maxVal;
      } else {
        $value = $isNumeric ? floatval($value) : $value;
        $field['und'][$delta][$sub_field] = $value;
      }
    }

    $delta++;
  }
  $entity->$field_name = $field;
}